# root
GET http://localhost:3000/
Authorization: Basic TWFzdGVyczpBY2FkZW15
###

GET http://localhost:3000/task/max
###

GET http://localhost:3000/task/filter?field=type&value=socks
###

GET http://localhost:3000/task/format?field=type&value=socks
###

GET http://localhost:3000/discount/callback
###

GET http://localhost:3000/discount/promise
###

GET http://localhost:3000/discount/async
###

GET http://localhost:3000/products/store/default
###

POST http://localhost:3000/products/store/set-products HTTP/1.1
content-type: application/json

{
  "data" : [
    { "type": "socks", "color": "red", "quantity": "10", "priceForPair": "$3" },
    { "type": "socks", "color": "green", "quantity": "5", "priceForPair": "$10" }
  ]
}
###

GET http://localhost:3000/store/list
###

POST http://localhost:3000/store/optimize HTTP/1.1
content-type: application/json

{ "filename" : "example_name.json" }
###

GET http://localhost:3000/db/allproducts
###

POST http://localhost:3000/db/products/create HTTP/1.1
content-type: application/json

{ "type": "gloves", "color":"red", "quantity":10, "price":5 }
###

GET http://localhost:3000/db/products/reed?id=11
###

GET http://localhost:3000/db/products/delete?id=1
###

POST http://localhost:3000/db/products/update HTTP/1.1
content-type: application/json

{ "id": 1, "quantity": 19 }
###

POST http://localhost:3000/db/types/create HTTP/1.1
content-type: application/json

{ "name": "gloves" }
###

GET http://localhost:3000/db/types/reed?id=1
###

GET http://localhost:3000/db/types/delete?id=1
###

POST http://localhost:3000/db/types/update HTTP/1.1
content-type: application/json

{ "id": 1, "name": "socks" }
###

POST http://localhost:3000/db/colors/create HTTP/1.1
content-type: application/json

{ "name": "red" }
###

GET http://localhost:3000/db/colors/reed?id=1
###

GET http://localhost:3000/db/colors/delete?id=1
###

POST http://localhost:3000/db/colors/update HTTP/1.1
content-type: application/json

{ "id": 1, "name": "green" }
###
